global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'hedera-mrv'
    static_configs:
      - targets: ['hedera-mrv:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
